image:
  registry: docker.io
  repository: bitnami/redis
  # כאן זה תקין לרשום latest כי זה ה-Tag של Docker
  tag: latest
  auth:
    enabled: false
#    existingSecret: "redis-custom-password"
#    existingSecretPasswordKey: "redis-password"
    sentinel:
        enabled: false